from django.urls import path

from .views import *

urlpatterns = [
    path('', music_library, name='music_library_url'),
    path('songs/', SongsList.as_view(), name='songs_list_url'),
    path('songs/create/', SongsCreate.as_view(), name='songs_create_url'),
    path('songs/<str:song_id>/update/', SongsUpdate.as_view(), name='songs_update_url'),
    path('songs/<str:song_id>/delete/', SongsDelete.as_view(), name='songs_delete_url'),
    path('songs/authors/<str:id>/delete/', SongsAuthorsDelete.as_view(), name='songs_authors_delete_url'),
    path('songs/authors/add/', SongsAuthorsAdd.as_view(), name='songs_authors_add_url'),
    path('albums/', AlbumsList.as_view(), name='albums_list_url'),
    path('albums/create/', AlbumsCreate.as_view(), name='albums_create_url'),
    path('albums/<str:slug>/', AlbumsDetail.as_view(), name='albums_detail_url'),
    path('albums/<str:slug>/update/', AlbumsUpdate.as_view(), name='albums_update_url'),
    path('albums/<str:slug>/delete/', AlbumsDelete.as_view(), name='albums_delete_url'),
    path('artists/', ArtistsList.as_view(), name='artists_list_url'),
    path('artists/create/', ArtistsCreate.as_view(), name='artists_create_url'),
    path('artists/<str:slug>/', ArtistsDetail.as_view(), name='artists_detail_url'),
    path('artists/<str:slug>/update/', ArtistsUpdate.as_view(), name='artists_update_url'),
    path('artists/<str:slug>/delete/', ArtistsDelete.as_view(), name='artists_delete_url'),
    path('genres/', GenresList.as_view(), name='genres_list_url'),
    path('genres/create/', GenresCreate.as_view(), name='genres_create_url'),
    path('genres/<str:slug>/', GenresDetail.as_view(), name='genres_detail_url'),
    path('genres/<str:slug>/update/', GenresUpdate.as_view(), name='genres_update_url'),
    path('genres/<str:slug>/delete/', GenresDelete.as_view(), name='genres_delete_url'),
    path('labels/', LabelsList.as_view(), name='labels_list_url'),
    path('labels/create/', LabelsCreate.as_view(), name='labels_create_url'),
    path('labels/<str:slug>/', LabelsDetail.as_view(), name='labels_detail_url'),
    path('labels/<str:slug>/update/', LabelsUpdate.as_view(), name='labels_update_url'),
    path('labels/<str:slug>/delete/', LabelsDelete.as_view(), name='labels_delete_url'),
    path('producers/', ProducersList.as_view(), name='producers_list_url'),
    path('producers/create/', ProducersCreate.as_view(), name='producers_create_url'),
    path('producers/<str:slug>/', ProducersDetail.as_view(), name='producers_detail_url'),
    path('producers/<str:slug>/update/', ProducersUpdate.as_view(), name='producers_update_url'),
    path('producers/<str:slug>/delete/', ProducersDelete.as_view(), name='producers_delete_url'),
    path('authors/', AuthorsList.as_view(), name='authors_list_url'),
    path('authors/create/', AuthorsCreate.as_view(), name='authors_create_url'),
    path('authors/<str:slug>/', AuthorsDetail.as_view(), name='authors_detail_url'),
    path('authors/<str:slug>/update/', AuthorsUpdate.as_view(), name='authors_update_url'),
    path('authors/<str:slug>/delete/', AuthorsDelete.as_view(), name='authors_delete_url'),
    path('charts/', Charts.as_view(), name='charts_url'),
]
